export const EVENT_CATEGORIES = [
	"Politics",
	"Wars & Conflicts",
	"Disasters",
	"Deaths",
	"Science & Technology",
	"Space",
	"Health",
	"Economy",
	"Culture",
	"Sports",
	"Entertainment",
	"Crime",
	"Protests & Movements",
	"Companies & Products",
	"Internet & Media",
] as const;